# -*- coding: utf-8 -*-
"""Pc_componentes2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tF4Se7d8qyAa7TVmr7psdwIrEjyJ5WC4
"""

!pip install google-play-scraper pandas

from google_play_scraper import Sort, reviews_all
import pandas as pd
import time

# 1. ID ACTUALIZADO de la App de PcComponentes
app_id = 'com.vidibond.pccomponentes2'

print(f"Iniciando el scraping de {app_id}... Esto puede tardar unos segundos.")

# 2. Extracción de reseñas (Filtramos por idioma y país para Murcia/España)
result = reviews_all(
    app_id,
    sleep_milliseconds=1000, # Pausa de 1s para mayor estabilidad
    lang='es',
    country='es',
    sort=Sort.NEWEST
)

if not result:
    print("❌ ERROR: Siguen sin aparecer reseñas. Prueba quitando los filtros de país/idioma.")
else:
    print(f"✅ ¡Éxito! Se han extraído {len(result)} reseñas reales.")

    # 3. Procesamiento y limpieza
    df = pd.DataFrame(result)

    # Verificamos que las columnas existan antes de filtrar
    if 'score' in df.columns:
        df_final = df[['score', 'content', 'at']].copy()
        df_final.columns = ['Estrellas', 'Comentario', 'Fecha']

        # Guardamos el archivo para tu análisis en R
        df_final.to_excel("pccomponentes_app_reviews.xlsx", index=False)
        print("📁 Archivo 'pccomponentes_app_reviews.xlsx' generado con éxito.")
    else:
        print("⚠️ Error inesperado en el formato de los datos de Google.")