# -*- coding: utf-8 -*-
"""Pc_componentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tF4Se7d8qyAa7TVmr7psdwIrEjyJ5WC4
"""

!pip install google-play-scraper pandas

import pandas as pd
from google_play_scraper import Sort, reviews
from IPython.display import display

print("Conectando directamente con la base de datos de Google Play Store...")

# Este es el ID oficial de la app de PC Componentes en Android
app_id = 'com.vidibond.pccomponentes2'

print("Descargando 1.000 opiniones reales (Esto tardará 3 segundos)...")

# Magia pura: extraemos 1000 reseñas sin bloqueos
opiniones, _ = reviews(
    app_id,
    lang='es', # Idioma español
    country='es', # Tienda de España
    sort=Sort.NEWEST, # Las más recientes primero
    count=1000 # Cantidad exacta que queremos
)

print(f"¡Boom! Se han extraído {len(opiniones)} opiniones de clientes reales.")

# 3. Limpiamos y estructuramos los datos para tu Máster
datos_limpios = []
for op in opiniones:
    datos_limpios.append({
        "Estrellas": op['score'],
        "Fecha": op['at'],
        "Útil_para_otros": op['thumbsUpCount'], # Esto indica si más gente piensa igual
        "Comentario": op['content']
    })

df = pd.DataFrame(datos_limpios)

# Nos aseguramos de que no haya comentarios vacíos
df = df[df['Comentario'].notna()]
df = df[df['Comentario'].str.strip() != '']

# Guardamos tu tesoro en Excel (CSV)
nombre_archivo = "pccomponentes_app_reviews.csv"
df.to_csv(nombre_archivo, index=False, encoding='utf-8')

print(f"¡Guardado con éxito! Abre la carpeta de la izquierda para descargar tu archivo '{nombre_archivo}'.")

# un pequeño aperitivo de lo que se ha conseguido en un df head
display(df.head())
# Aseguramos que Colab tiene la librería para escribir Excels
!pip install openpyxl

# dataframe 'df' ya tiene los datos limpios de antes
# Vamos a exportarlo directamente a formato Excel (.xlsx)
nombre_archivo_excel = "pccomponentes_app_reviews.xlsx"

# Lo guardo  usando el motor de Excel
df.to_excel(nombre_archivo_excel, index=False, engine='openpyxl')

print(f" ¡Perfecto! Tu archivo '{nombre_archivo_excel}' está listo para RStudio.")